export const FLAGS: Record<string, string> = {
  Argentina:             "🇦🇷",
  Australia:             "🇦🇺",
  Austria:               "🇦🇹",
  Belgium:               "🇧🇪",
  Bolivia:               "🇧🇴",
  "Bosnia & Herzegovina":"🇧🇦",
  Brazil:                "🇧🇷",
  Cameroon:              "🇨🇲",
  Canada:                "🇨🇦",
  "Cape Verde":          "🇨🇻",
  Chile:                 "🇨🇱",
  Colombia:              "🇨🇴",
  "Congo DR":            "🇨🇩",
  "Costa Rica":          "🇨🇷",
  Croatia:               "🇭🇷",
  Denmark:               "🇩🇰",
  Ecuador:               "🇪🇨",
  Egypt:                 "🇪🇬",
  England:               "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  France:                "🇫🇷",
  Germany:               "🇩🇪",
  Ghana:                 "🇬🇭",
  Honduras:              "🇭🇳",
  Hungary:               "🇭🇺",
  Indonesia:             "🇮🇩",
  Iran:                  "🇮🇷",
  "Ivory Coast":         "🇨🇮",
  Japan:                 "🇯🇵",
  "Korea Republic":      "🇰🇷",
  "South Korea":         "🇰🇷",
  Mexico:                "🇲🇽",
  Morocco:               "🇲🇦",
  Netherlands:           "🇳🇱",
  "New Zealand":         "🇳🇿",
  Nigeria:               "🇳🇬",
  Panama:                "🇵🇦",
  Paraguay:              "🇵🇾",
  Peru:                  "🇵🇪",
  Poland:                "🇵🇱",
  Portugal:              "🇵🇹",
  Qatar:                 "🇶🇦",
  Romania:               "🇷🇴",
  "Saudi Arabia":        "🇸🇦",
  Scotland:              "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Senegal:               "🇸🇳",
  Serbia:                "🇷🇸",
  Slovenia:              "🇸🇮",
  Spain:                 "🇪🇸",
  Switzerland:           "🇨🇭",
  Tunisia:               "🇹🇳",
  Turkey:                "🇹🇷",
  "Türkiye":             "🇹🇷",
  Ukraine:               "🇺🇦",
  "United States":       "🇺🇸",
  USA:                   "🇺🇸",
  Uruguay:               "🇺🇾",
  Venezuela:             "🇻🇪",
  Wales:                 "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
}

export function getFlag(name: string | null | undefined): string {
  if (!name) return ""
  return FLAGS[name] ?? ""
}
